theme: jekyll-theme-slate
title: Sirius' blog
description: 黄沙百战穿金甲，不破楼兰誓不还
author: sirius
timezone: Asia/Beijing
jekyll-archives:
  enabled:
    -categories
    -tags
defaults:
  - scope:
      path: "file"
    values:
      pdf: true
  - scope:
      path: "assets"
    values:
      image: true
